//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// TeamProject.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_TEAMPROJECT_FORM            101
#define IDP_FAILED_OPEN_DATABASE        103
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_TeamProjectTYPE             130
#define ID_WINDOW_MANAGER               131
#define IDS_EDIT_MENU                   306
#define IDD_BASEINFOVIEW                310
#define IDR_MENU_BASEINFO               311
#define IDR_BASEINFOVIEW_TMPL           312
#define IDD_DIALOG_INFOMANAGE           312
#define IDD_DIALOG_REGBASE              312
#define IDD_INFOMANAGEVIEW              313
#define IDD_DIALOG_BASECONF             314
#define IDD_DIALOG1                     315
#define IDD_DIALOG_CHECK                315
#define IDD_DIALOG2                     316
#define IDD_CHECKVIEW2                  317
#define IDD_EQUIPSTATUSVIEW             318
#define IDD_CHECKVIEW                   319
#define IDD_LOADINGDLG                  320
#define IDD_DIALOG_CHART                328
#define IDD_TAB_EQUIPSTATUS             330
#define IDD_TAB_ERROREQUIPSTATUS        331
#define IDD_TAB_SECURITYLOG             333
#define IDD_DIALOG3                     334
#define IDD_TAB_EVENT_LOG               334
#define IDB_BITMAP_LOGO                 339
#define IDC_COMBO_GROUP                 1003
#define IDC_COMBO_GROPNAME1             1003
#define IDC_COMBO_COMPANY               1004
#define IDC_COMBO_GROPNAME2             1004
#define IDC_BUTTON_ADD                  1005
#define IDC_EDIT_QR                     1006
#define IDC_EDIT_BASELOC                1007
#define IDC_EDIT_LOCATIONNAME           1007
#define IDC_EDIT_BASEID                 1008
#define IDC_EDIT_MANAGENUM              1009
#define IDC_EDIT_INSTCLASS              1010
#define IDC_EDIT_INSTALLATIONCLASSIFICATION 1010
#define IDC_EDIT_INSTLOC                1011
#define IDC_EDIT_INSTALLATIONADDRESS    1011
#define IDC_EDIT_LATITUDE               1012
#define IDC_EDIT_LONGITUDE              1013
#define IDC_BUTTON_SELECT               1014
#define IDC_EDIT_IP                     1015
#define IDC_EDIT_PORT                   1016
#define IDC_COMBO_DATE                  1017
#define IDC_EDIT_INSTCOMPANY            1018
#define IDC_EDIT_MAINTCOMPANY           1019
#define IDC_EDIT_PHONEONE               1020
#define IDC_EDIT_PHONETWO               1021
#define IDC_EDIT_PHONETHREE             1022
#define IDC_COMBO_STATE                 1023
#define IDC_LIST1                       1024
#define IDC_LIST_BASE                   1024
#define IDC_EDIT_LOCATIONADDRESS        1024
#define IDC_LIST_DATA                   1024
#define IDC_LIST_DATA2                  1024
#define IDC_TAB1                        1025
#define IDC_BUTTON_SEARCH               1026
#define IDC_BUTTON_COPY                 1027
#define IDC_BUTTON_SAVE                 1028
#define IDC_BUTTON_EDIT                 1029
#define IDC_BUTTON_CANCEL               1030
#define IDC_STATIC_MODELNAME            1033
#define IDC_EDIT_MODELNAME              1034
#define IDC_EDIT_EQUIPMENT              1034
#define IDC_COMBO_DEPARTMENT            1035
#define IDC_COMBO_PURPOSE               1038
#define IDC_COMBO3                      1041
#define IDC_EDIT_MANUFACTURER           1042
#define IDC_EDIT_MAINTAINER             1043
#define IDC_EDIT8                       1044
#define IDC_EDIT9                       1045
#define IDC_EDIT10                      1046
#define IDC_BUTTON_SELECTBASE           1048
#define IDC_BUTTON_SELECTDEVICE         1049
#define IDC_BUTTON_ADDDEPARTMENT        1050
#define IDC_BUTTON_ADDPURPOSE           1051
#define IDC_LIST_DEVICE                 1053
#define IDC_LIST_HISTORY                1054
#define IDC_LIST_REQUEST                1055
#define IDC_EDIT_REQUEST                1056
#define IDC_COMBO_REQUEST               1057
#define IDC_BUTTON_REQUEST              1059
#define IDC_TAB_CHECK_2                 1060
#define IDC_COMBO_VIEW                  1061
#define IDC_EXPLORER1                   1062
#define IDC_CHART                       1063
#define IDC_BUTTON_CHARTVIEW            1064
#define IDC_TAB_EQUIPSTATUS             1065
#define IDC_TAB_BASEINFOVIEW            1066
#define IDC_BUTTON1                     1069
#define IDC_BUTTON2                     1070
#define IDC_EVENTLIST                   1072
#define IDC_EDIT3                       1073
#define IDC_ERRORREASON                 1073
#define IDC_EDIT4                       1074
#define IDC_INSTALLLOCNAME              1074
#define IDC_LOCATENAME                  1076
#define IDC_INOUTNAME                   1077
#define IDC_SECURITYLIST                1080
#define IDC_EVENTCONTEXT                1081
#define IDC_OCCURDATE                   1082
#define IDC_ENTERTIME                   1083
#define IDC_OUTTIME                     1084
#define IDC_EQUIPSTATUS                 1086
#define IDC_LISTEQUIPSTATUS             1087
#define IDC_LIST_ERR_EQUIP_STATUS       1090
#define IDC_BUTTON_DELETE               1091
#define IDD_EQUIPCHECKLIST              12000
#define IDC_HUBNAME                     21057
#define IDC_INSTALLLOC                  21058
#define IDC_EQUIPTYPE                   21059
#define IDC_CHECKTYPE                   21060
#define IDC_REQUESTDATE                 21061
#define IDC_CHECKDATE                   21062
#define IDC_CheckConfirm                21063
#define IDC_EXPLORER_MAP                31055
#define IDD_DIALOG_MAP                  31056
#define IDC_EDIT_PHONE                  31057
#define IDC_EDIT1                       31058
#define IDC_EDIT2                       31059

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        342
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           321
#endif
#endif
